######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 16 03:56:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ai.h gamegrid.h gobanggame.h mainwindow.h ui_mainwindow.h
SOURCES += ai.cpp gamegrid.cpp gobanggame.cpp main.cpp mainwindow.cpp
